name: Bad Case Report of the model
description: Report a bug related to the model to help us reproduce and fix the problem.
title: "[Model BadCase]: "

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reaching out! Please make sure to check the [GitHub README](https://github.com/MiniMax-AI/MiniMax-M2.1) of the model and the [MiniMax Documentation](https://platform.minimax.io/docs/guides/models-intro)

  - type: input
    id: Models-Used
    attributes:
      label: Basic Information - Models Used
      description: |
        Please list the model used, e.g., MiniMax-M2.1, speech-2.6-hd, etc.
        (Note: You can refer to our models at [HuggingFace](https://huggingface.co/MiniMaxAI) or [the official site](https://www.minimax.io/platform_overview) for more details.)
      placeholder: "eg: MiniMax-M2.1"
    validations:
      required: true

  - type: textarea
    id: Environment-and-Deployment-Info
    attributes:
      label: Information about environment and deployment
      description: |
        (Include software versions, OS, GPUs if applicable)
      placeholder: |
        For example:
        - OS: Ubuntu 24.04
        - Python: Python 3.11
        - PyTorch: 2.6.0+cu124

        Deployment Command: python run_inference.py --model my_model --config config.yaml
    validations:
      required: true

  - type: textarea
    id: description-of-bug
    attributes:
      label: Description
      description: |
        Please **describe the bad case** you have encountered and **paste the screenshots** if available.
      value: |
        ## Steps to reproduce
        The bug can be reproduced with the following steps:

        ## Expected behavior

        ## Error logs

        ## Paste the related screenshots here

    validations:
      required: true
